### ISSUE TITLE
Can't deserialize 0-subunit values from dicts

### ISSUE THREAD

**Issue by mahmoud** [antonagestam/immoney#51]
Hey there, I noticed that `Money(0, USD)` works fine, but that deserializing from `{'currency': 'USD', 'subunits': 0} doesn't.

The culprit seems to be this line:

https://github.com/antonagestam/immoney/blob/5608d2e7a46b4b304c0e29068630ec7ea1a5dbf3/src/immoney/_pydantic.py#L113

Fairly certain that `gt` should be a `ge`. What do you think?

**Comment by antonagestam** [comment]
Hi! Thanks for reporting this. I think you're assessment is correct, this looks like a bug.

**Comment by mahmoud** [comment]
Cool. I've patched locally for now. Note that there's also a `gt=0` on `Overdraft`. The usefulness of a monetary `-0.00` is somewhat debatable, and I'll leave that for a future issue.

**Comment by antonagestam** [comment]
@mahmoud Yeah, that's intentional, I'd much rather have no overlap between Money and Overdraft.

**Comment by antonagestam** [comment]
> @mahmoud Yeah, that's intentional, I'd much rather have no overlap between Money and Overdraft.

Actually, I'll retract this statement, as it's already valid to instantiate `Overdraft` with a `0` value.

**Comment by mahmoud** [comment]
Your call. :) But I could see the eventual question of equivalence btwn `Overdraft(0)` and `Money(0)`. Much as it's argued in the README that there's no valid "negative money" I'd be astonished to be presented with a `0`-valued overdraft. Happy to chat about it on Discussions or Discord.

**Comment by antonagestam** [comment]
@mahmoud Yeah, that's my reasoning too I think. I changed already so that schema is in line with the type itself, but am open to changing that behavior.

**Comment by antonagestam** [comment]
@mahmoud I created #58 and related #59. Are you interested in working on this?
