### ISSUE TITLE
Streamline/document development setup

### ISSUE THREAD

**Issue by mahmoud** [antonagestam/immoney#52]
Just running the tests against a change for #51, and I had to do some guesswork. Maybe a section at the bottom of the readme like:

```
# Development setup

$ python3.10 -m venv venv
$ source venv/bin/activate
$ pip install requirements.txt
```

You know best, but right now my requirements looks like:

```
# from pip freeze
abcattrs==0.4.0
annotated-types==0.5.0
attrs==23.1.0
cachetools==5.3.1
chardet==5.2.0
colorama==0.4.6
distlib==0.3.7
exceptiongroup==1.1.3
filelock==3.12.2
hypothesis==6.82.6
iniconfig==2.0.0
packaging==23.1
platformdirs==3.10.0
pluggy==1.2.0
pydantic==2.3.0
pydantic_core==2.6.3
pyproject-api==1.5.4
pytest==7.4.0
sortedcontainers==2.4.0
tomli==2.0.1
tox==4.10.0
typing_extensions==4.7.1
```

Also, might I recommend [`tox`](https://tox.wiki/) for cross-python testing? Your pytest setup should be basically-drop in, and that way you can easily switch between testing 3.10 and 3.11. Developers would only need to `pip install tox` and then run `tox`.

**Comment by antonagestam** [comment]
Thanks for making this inquiry, I've now added development instructions in #55.

I'm open to accepting a tox configuration, but I'm not keen to spend time on it myself in the short term. For this project I'll likely keep developing against a single version locally for the foreseeable future. If it's something you're interested in seeing happening, do feel free to open a PR.
